coverage:
  round: up

  status:
    project:
      default:
        target: auto
        threshold: 2%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 5%
        base: auto
